### ISSUE TITLE
mods_to_dc.xsl default

### ISSUE THREAD

**Issue by uconnjeustis** [islandora-interest-groups/Islandora-Metadata-Interest-Group#15]
There has been several discussions on the Google list about this transformation which is from LC. The most recent conversation is https://groups.google.com/forum/#!topic/islandora/5yO9NkEBpI0. Here, it was noted that the subjects are mapped all to one dc.subject field. This default is not changed or modified in core released. But it seems that many have change this transformation.

We're interested in knowing:
Have you made changes to this default transformation? What were those changes and would you be willing to share your transformation publicly?

Would people be interested in gathering suggestions or even sample changes that we can share with LC to improve the  mods to dc transformation?

**Comment by mjordan** [comment]
Also relevant: https://jira.duraspace.org/browse/ISLANDORA-1462.

**Comment by amandarl** [comment]
I have made small changes specific to our cataloging and display needs - not things that I would suggest need to be institutionalized.  However I basically had to teach myself how to do this, and didn't take the time to document because I lacked the confidence.  

So I would suggest documenting good practices for modifying the transformations for your institution, and maybe a github spot to store exemplary ones.  I could especially note things like keeping track of which transformation(s) you want to edit among all of the scattered files, are the locations comprehensively listed [on the wiki] (https://github.com/Islandora/islandora/wiki/LOC-transforms)?).  

Also, [ISLANDORA-1018](https://jira.duraspace.org/browse/ISLANDORA-1018) may also be relevant.

**Comment by SedizioseVoci** [comment]
We've made several edits to the xslt. One of them addresses the
smushed-together MODS subjects problem. Like Amanda, we've also made edits
to address purely local needs. Many are probably too institution-specific
to be candidates for inclusions in a list of suggested changes for LC's
master xslt. They mostly have to do with getting our data to load and
display properly in DPLA. A few are:

* The out-of the-box mods_to_dc_oai xslt was mapping our MODS genre terms
to dc:type, which our local DPLA hub was unhappy about (reasonably enough,
they want only DCMI terms for this element). We made adjustments so that
our genre terms are mapped to dc:format.

* We are using MODS <partNumber> with titles in one collection. Because the
Islandora public display won't show part numbers in titles in results lists
or at the collection view, we had to insert them redundantly at the end of
<title> to make them visible. The xslt slaps MODS partNumbers on the end of
dc:title (something we wish Islandora could do in MODS in public displays),
which will result in double "part number" values when the data is
harvested. So that part had to be stripped out. (We're keeping the
partNumber in place for sorting purposes--something else Islandora has
trouble doing with ease.)

* We changed the xslt to prevent all elements except the MODS abstract from
mapping to dc:description. Formerly lots of other random descriptive stuff
in MODS (various notes, etc.) that the xslt maps to dc:description was
cluttering up the displays of our data in DPLA.

Would be interested in seeing others' changes (and would be willing to
share my clunky edits), and agree that sample changes to improve the DC
transformation would be helpful.

Joseph
